### ISSUE TITLE
language

### ISSUE THREAD

**Issue by francescoagati** [brh55/google-news-rss#2]
the possibility of select the langugage feed can be nice

**Comment by brh55** [comment]
@francescoagati nice suggestion!

I'll do that once I resolve all the minor parsing issues. 👍  Thanks for the suggestion!

**Comment by adalbueno** [comment]
I also need it and I can contribute developing it...

**Comment by adalbueno** [comment]
Issue fixed ;)

@brh55 
@francescoagati

**Comment by francescoagati** [comment]
thanks :-)
