### ISSUE TITLE
google-news-rss is removing words from the description

### ISSUE THREAD

**Issue by tomlister** [brh55/google-news-rss#6]
According to a Google translation of orders, Putin has tasked the Russian government with determining how like , the smart contract technology used by the network, and the tokens released during Initial Coin Offerings .

Notice the missing words 👎

**Comment by tomlister** [comment]
Another example... It appears it's removing key search terms.

The story of and the blockchain go back just a short while with a white paper published by Satoshi Nakamoto in October 2008.

**Comment by brh55** [comment]
I see what you mean. Looks like it's stripping a bit of the content rather than just the unescaped HTML chars.

**Comment by brh55** [comment]
@tomlister latest v0.2.1 should fix this now 👍  thanks for the open issue!

**Comment by tomlister** [comment]
@brh55 Thanks mate
