### ISSUE TITLE
Google News RSS deprecation

### ISSUE THREAD

**Issue by alopix** [brh55/google-news-rss#7]
Great idea, but unfortunately Google is going to shut down the RSS feed you're using in around 1.5 weeks.
The very first entry in the resulting RSS feed will also show that deprecation. You can find the new RSS links at the bottom of the http://news.google.com/news pages.

**Comment by brh55** [comment]
@alopix Good to know! Seems this may require a complete re-work for the new URLs assuming the parameters are bound to change as well

**Comment by brh55** [comment]
The following PR (#8) and version 0.3.0 should address the deprecation issues. 

However, I wasn't able to find any information regarding the new url scheme so I had to tinker/reverse engineer the urls until I was able to get search working again. I can't guarantee it's perfect, but for the most part everything is working 👍 .
